Updating the Files in the repository
- Adding tmux, nvim, waybar, mpd, mpv configs

diff --git a/private_dot_zshrc b/private_dot_zshrc
--- a/private_dot_zshrc
+++ b/private_dot_zshrc
@@ -3,6 +3,31 @@ if [[ ":$FPATH:" != *":/home/jere/.zsh/completions:"* ]]; then export FPATH="/ho
 # If you come from bash you might have to change your $PATH.
 # export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
 
+compile_then_source() {
+  local method=$1       # '.' or 'source'
+  local file=$2         # file to source
+  shift 2
+  local args=("$@")     # remaining args passed to the sourced file
+
+  # Bash compatibility
+  if [[ $BASH_VERSION ]]; then
+    eval builtin "$method" "$file" "${args[@]@Q}"
+    return $?
+  fi
+
+  # Zsh: check if .zwc is missing or outdated
+  if [[ ! $file.zwc -nt $file ]]; then
+    if [[ -r $file && -w ${file:h} ]]; then
+      zcompile "${file:P}"
+    fi
+  fi
+
+  # Source the file with any args
+  eval builtin "$method" "$file" "${(q)args[@]}"
+}
+
+compile_then_source source "$HOME/.zshrc.d/tmux.zsh"
+
 # Path to your Oh My Zsh installation.
 export ZSH="$HOME/.oh-my-zsh"
 
@@ -10,7 +35,7 @@ export ZSH="$HOME/.oh-my-zsh"
 # load a random theme each time Oh My Zsh is loaded, in which case,
 # to know which specific one was loaded, run: echo $RANDOM_THEME
 # See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
-ZSH_THEME="amuse"
+ZSH_THEME="avit"
 
 # Set list of themes to pick from when loading at random
 # Setting this variable when ZSH_THEME=random will cause zsh to load
@@ -76,14 +101,14 @@ zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'
 
 
 fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src
-autoload -U compinit && compinit
+#autoload -U compinit && compinit
 
 # Which plugins would you like to load?
 # Standard plugins can be found in $ZSH/plugins/
 # Custom plugins may be added to $ZSH_CUSTOM/plugins/
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
-plugins=(git zoxide fzf aliases alias-finder archlinux colored-man-pages zsh-autosuggestions zsh-syntax-highlighting cp bgnotify)
+plugins=(git zoxide fzf alias-finder archlinux colored-man-pages zsh-autosuggestions zsh-syntax-highlighting cp)
 
 source $ZSH/oh-my-zsh.sh
 
@@ -94,21 +119,40 @@ source $ZSH/oh-my-zsh.sh
 # You may need to manually set your language environment
 # export LANG=en_US.UTF-8
 
-# Preferred editor for local and remote sessions
-if [[ -n $SSH_CONNECTION ]]; then
-  export EDITOR='vim'
-else
-  export EDITOR='nvim'
-fi
+# History
+HISTSIZE=50000
+HISTFILE=~/.zsh_history
+SAVEHIST=$HISTSIZE
+HISTDUP=erase
+setopt appendhistory
+setopt sharehistory
+setopt hist_ignore_space
+setopt hist_ignore_all_dups
+setopt hist_save_no_dups
+setopt hist_ignore_dups
+setopt hist_find_no_dups
 
-# Lines configured by zsh-newuser-install
-# HISTFILE=~/.histfile
-# HISTSIZE=10000
-# SAVEHIST=1000
 setopt autocd
 bindkey -e
-# End of lines configured by zsh-newuser-install
 #zstyle :compinstall filename '/home/jere/.zshrc'
+
+## colors
+# To have colors for ls and all grep commands such as grep, egrep and zgrep
+export CLICOLOR=1
+export LS_COLORS='no=00:fi=00:di=00;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:*.xml=00;31:'
+#export GREP_OPTIONS='--color=auto' #deprecated
+alias grep="/usr/bin/grep $GREP_OPTIONS"
+unset GREP_OPTIONS
+
+# Color for manpages in less makes manpages a little easier to read
+export LESS_TERMCAP_mb=$'\E[01;31m'
+export LESS_TERMCAP_md=$'\E[01;31m'
+export LESS_TERMCAP_me=$'\E[0m'
+export LESS_TERMCAP_se=$'\E[0m'
+export LESS_TERMCAP_so=$'\E[01;44;33m'
+export LESS_TERMCAP_ue=$'\E[0m'
+export LESS_TERMCAP_us=$'\E[01;32m'
+
 
 autoload -Uz add-zsh-hook
 
@@ -128,10 +172,22 @@ if [ ! -d "$HOME/.zshrc.d" ]; then
 	mkdir -p "$HOME/.zshrc.d";
 fi
 
-for cfg in $HOME/.zshrc.d/*.zsh; do
-    source "$cfg"
+
+# Define your array of file paths
+files=(
+  "$HOME/.zshrc.d/aliases.zsh"
+  "$HOME/.zshrc.d/path.zsh"
+)
+
+# Loop through and source each file
+for file in "${files[@]}"; do
+  if [[ -f "$file" ]]; then
+    compile_then_source source "$file"
+  else
+    echo "Warning: File not found - $file"
+  fi
 done
-unset -v cfg
+
 
 source "$HOME/.homesick/repos/homeshick/homeshick.sh"
 fpath=($HOME/.homesick/repos/homeshick/completions $fpath)
@@ -145,6 +201,28 @@ esac
 # pnpm End
 
 # Put this in ~/.zshrc
+
+
+# Attach to an existing tmux session, default to main_USER
+tmuxa() {
+  local session="${1:-main_${USER}}"
+  if tmux has-session -t "$session" 2>/dev/null; then
+    tmux attach-session -t "$session"
+  else
+    echo "No tmux session named '$session' exists."
+  fi
+}
+
+# Create or switch to a named tmux session
+tmuxn() {
+  local session="${1:-main_${USER}}"
+  if tmux has-session -t "$session" 2>/dev/null; then
+    tmux switch-client -t "$session"
+  else
+    tmux new-session -s "$session"
+  fi
+}
+
 
 
 # Compilation flags
